// store/counterSlice.ts
import { createSlice } from '@reduxjs/toolkit';

// Define the initial state of the counter
const initialState = {
  authenticated: false,
};

// Create a slice for the counter
export const userSlice = createSlice({
  name: 'user',
  initialState,
  reducers: {
    authenticate: (state) => {
      state.authenticated = !state.authenticated;
    },
  },
});

// Export actions generated by the slice
export const { authenticate } = userSlice.actions;

// Export the reducer
export default userSlice.reducer;
